markdown: redcarpet
name: Enterprise Business Architecture Guide
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: Province of British Columbia
  url: https://www.gov.bc.ca

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/bc_logo_transparent.png
logoalt: BC logo

repo_url: https://github.com/bcgov/eba-guide

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here
navigation:

- text: Introduction
  internal: true
- text: Alignment Model
  url: eba_AlignmentModel/
  internal: true
- text: EBA Outcomes
  url: eba_outcomes/
  internal: true
- text: EBA and the New Solution Domains
  url: eba_newdomains/
  internal: true
  children:
  - text: Domain & Impact on Service Transformation
    url: eba_domain_impact/
    internal: true
- text: The EBA Context
  url: eba_context/
  internal: true
  children:
  - text: Input Strategic Intent & Business Priorities
    url: eba_context_input/
    internal: true
  - text: Output Technology Enablers
    url: eba_context_output/
    internal: true
  - text: Guidance Business Enablers
    url: eba_context_guidance/
    internal: true
- text: Overview of the EBA Framework
  url: eba_frmwk_overview/
  internal: true
  children:
  - text: Layer 1
    url: eba_fmwkoverview_layer1/
    internal: true
  - text: Layer 2
    url: eba_fmwkoverview_layer2/
    internal: true
  - text: Layer 3
    url: eba_fmwkoverview_layer3/
    internal: true
  - text: Layer 4
    url: eba_fmwkoverview_layer4/
    internal: true
- text: Exploring the EBA Framework
  url: eba_framework/
  internal: true
- text: Using the EBA for Business Results
  url: eba_bus_results/
  internal: true
  children:
  - text: EBA & the Initiative Lifecycle
    url: eba_busresults_lifecycle/
    internal: true
- text: The EBA Alignment Process
  url: eba_align_process/
  internal: true
- text: The EBA Refreshment Cycle
  url: eba_refresh/
  internal: true

repos:
- name: EBA Guide
  description: Main repository
  url: https://github.com/bcgov/eba-guide


back_link:
  url: "http://guides.pathfinder.bcgov"
  text: Read more BC Government Guides

google_analytics_ua: UA-48605964-19

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "bc_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
